Topic/qiy scheme releases
qiyfoundation/Qiy-Scheme pull request #26
Opened 2018-07-26 13:01 UTC by 14665

2018-07-26 13:06 UTC, fdriesenaar approved these changes

2018-08-22 11:41 UTC, mlouman requested changes

2018-08-22 11:41 UTC, mlouman commented on Qiy Scheme Releases.md
> +The Supervisory Authority of the Qiy Foundation decides upon the release of new versions of the Qiy Scheme:
The Executive Board of the Qiy Foundation decides upon the release of new versions of the Qiy Scheme:

2018-08-22 11:41 UTC, mlouman commented on Qiy Scheme Releases.md
> +* The Supervisory Authority will release a major version when it introduces incompatible changes.
Supervisory Authority = Executive Board

2018-08-22 11:41 UTC, mlouman commented on Qiy Scheme Releases.md
> +* The Supervisory Authority will release a minor version when functionality is added in a backwards-compatible manner.
Supervisory Authority = Executive Board

2018-08-22 11:41 UTC, mlouman commented on Qiy Scheme Releases.md
> +* The Supervisory Authority will release a patch version for backwards-compatible (bug) fixes.
Supervisory Authority = Executive Board

2018-08-22 11:41 UTC, mlouman commented on Qiy Scheme Releases.md
> +The Supervisory Authority will follow these rules:
The Supervisory Authority = The Executive Board

2019-05-23 08:40 UTC, merged